/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
//#include <stdio.h>

static bool result = true;

void testfunction_startup(void)
{
}

void testfunction_PI_test_loop(void)
{
	volatile bool test_result = result;
}

void testfunction_PI_protected_provided_if_no_params(void)
{
	testfunction_RI_protected_required_if_no_params();
}


void testfunction_PI_protected_provided_if_with_params_in
      (const asn1SccMyInteger *IN_p1,
       const asn1SccMySeq *IN_p2,
       const asn1SccMyInteger *IN_p3,
       const asn1SccMySeq *IN_p4,
       const asn1SccMyInteger *IN_p5)

{
	if(*IN_p1 != 17){
		result = false;
	}

	if(IN_p2->input_data != 4001 || IN_p2->output_data != 1969 || IN_p2->validity != asn1SccMySeq_validity_invalid){
		result = false;
	}

	if(*IN_p3 != 17){
		result = false;
	}

	if(IN_p4->input_data != 4001 || IN_p4->output_data != 1969 || IN_p4->validity != asn1SccMySeq_validity_invalid){
		result = false;
	}

	if(*IN_p5 != 17){
		result = false;
	}

	testfunction_RI_protected_required_if_with_params_in(IN_p1, IN_p2, IN_p3, IN_p4, IN_p5);
}


void testfunction_PI_protected_provided_if_with_params_out
      (asn1SccMyInteger *OUT_p1,
       asn1SccMySeq *OUT_p2,
       asn1SccMyInteger *OUT_p3,
       asn1SccMySeq *OUT_p4,
       asn1SccMyInteger *OUT_p5)

{
	if(OUT_p1 == NULL){
		result = false;
	}

	if(OUT_p2 == NULL){
		result = false;
	}

	if(OUT_p3 == NULL){
		result = false;
	}

	if(OUT_p4 == NULL){
		result = false;
	}

	if(OUT_p5 == NULL){
		result = false;
	}

	testfunction_RI_protected_required_if_with_params_out(OUT_p1, OUT_p2, OUT_p3, OUT_p4, OUT_p5);
}


void testfunction_PI_sporadic_provided_if_no_param(void)
{
	testfunction_RI_sporadic_required_if_no_param();
}


void testfunction_PI_sporadic_provided_if_with_param
      (const asn1SccMySeq *IN_p1)

{
	if(IN_p1->input_data != 4001 || IN_p1->output_data != 1969 || IN_p1->validity != asn1SccMySeq_validity_invalid){
		result = false;
	}

	testfunction_RI_sporadic_required_if_with_param(IN_p1);
}


void testfunction_PI_unportected_provided_if_no_params(void)
{
	testfunction_RI_unportected_required_if_no_params();
}


void testfunction_PI_unprotected_provided_if_with_params_in
      (const asn1SccMyInteger *IN_p1,
       const asn1SccMySeq *IN_p2,
       const asn1SccMyInteger *IN_p3,
       const asn1SccMySeq *IN_p4,
       const asn1SccMyInteger *IN_p5)

{
	if(*IN_p1 != 17){
		result = false;
	}

	if(IN_p2->input_data != 4001 || IN_p2->output_data != 1969 || IN_p2->validity != asn1SccMySeq_validity_invalid){
		result = false;
	}

	if(*IN_p3 != 17){
		result = false;
	}

	if(IN_p4->input_data != 4001 || IN_p4->output_data != 1969 || IN_p4->validity != asn1SccMySeq_validity_invalid){
		result = false;
	}

	if(*IN_p5 != 17){
		result = false;
	}

	testfunction_RI_unprotected_required_if_with_params_in(IN_p1, IN_p2, IN_p3, IN_p4, IN_p5);
}


void testfunction_PI_unprotected_provided_if_with_params_out
      (asn1SccMyInteger *OUT_p1,
       asn1SccMySeq *OUT_p2,
       asn1SccMyInteger *OUT_p3,
       asn1SccMySeq *OUT_p4,
       asn1SccMyInteger *OUT_p5)

{
	if(OUT_p1 == NULL){
		result = false;
	}

	if(OUT_p2 == NULL){
		result = false;
	}

	if(OUT_p3 == NULL){
		result = false;
	}

	if(OUT_p4 == NULL){
		result = false;
	}

	if(OUT_p5 == NULL){
		result = false;
	}

	testfunction_RI_unprotected_required_if_with_params_out(OUT_p1, OUT_p2, OUT_p3, OUT_p4, OUT_p5);
}


