/* Body file for function samv71
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "samv71.h"
//#include <stdio.h>

void samv71_startup(void)
{
}

void samv71_PI_test_2
      (const asn1SccMyInteger *IN_param)

{
    asn1SccMyInteger param = (*IN_param) + 1;
    samv71_RI_response_2(&param);
}

void samv71_PI_test_4
      (const asn1SccMyInteger *IN_param)
{
    asn1SccMyInteger param = (*IN_param) + 1;
    samv71_RI_response_4(&param);
}
