/* Body file for function samv71
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "samv71.h"
//#include <stdio.h>


void samv71_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[samv71] Startup");
}

void samv71_PI_pong_sam
      (const asn1SccMyInteger *IN_param)

{
    samv71_RI_response(IN_param);
}


void samv71_PI_test
      (const asn1SccMyInteger *IN_param)

{
    samv71_RI_ping_sam(IN_param);
}


