/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_1.h"
#include <DeathReport.h>

extern const uint32_t DEATH_REPORT_BEGIN;

void function_1_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Function_1] Startup");
}

void function_1_PI_trigger(void)
{
	DeathReportWriter_DeathReport *const death_report = 
		(DeathReportWriter_DeathReport *const)&DEATH_REPORT_BEGIN;

	bool test_result = true;

	if(death_report->checksum == 0){
		test_result = false;
	}

	if(death_report->exception_id != 6){
		test_result = false;
	}

	if(death_report->registers.r2 != 4005){
		test_result = false;
	}

	if(death_report->stack_trace[2] != 4005){
		test_result = false;
	}

	(void)test_result;
}


