// C++ body file for function ponger
// Generated by TASTE (kazoo/templates/skeletons/cpp-body/function.tmplt)
// You can edit this file, it will not be overwritten

#include "ponger.h"
#include "ponger_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
ponger_state ctxt_ponger;


void ponger_startup(void)
{
}

void ponger_PI_ping(const asn1SccMyInteger *IN_param)

{
    asn1SccMyInteger number = *IN_param + 2;
    ponger_RI_pong(&number);
}


