/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Hal.h>

static uint64_t if_1_times[4];
static uint64_t if_2_times[2];
static uint32_t if_1_counter = 0;
static uint32_t if_2_counter = 0;
static bool test_result = false;


void testfunction_startup(void)
{
}

void testfunction_PI_PI_1(void)
{
    if_1_times[if_1_counter] = Hal_GetElapsedTimeInNs();
    if_1_counter++;
}


void testfunction_PI_PI_2(void)
{
    if_2_times[if_2_counter] = Hal_GetElapsedTimeInNs();
    if_2_counter++;
}

void testfunction_PI_trigger_check(void)
{
    if(if_1_counter == 4 && if_2_counter == 2 &&
        if_1_times[0] > 9500000 && if_1_times[0] < 10500000 &&
        if_1_times[1] > 19500000 && if_1_times[1] < 20500000 &&
        if_1_times[2] > 29500000 && if_1_times[2] < 30500000 &&
        if_1_times[3] > 39500000 && if_1_times[3] < 40500000 &&
        if_2_times[0] > 19500000 && if_2_times[0] < 20500000 &&
        if_2_times[1] > 39500000 && if_2_times[1] < 40500000){
        test_result = true;
    }
}


