/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <stdint.h>

void testfunction_startup(void)
{
}

void testfunction_protected_if(
       char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)
{
    asn1SccMySeq var;
    var.input_data = 42;
    var.output_data = 30;
    var.validity = asn1SccMyEnum_world;

    BitStream bit_stream;
    BitStream_Init(&bit_stream, OUT_p1, asn1SccMySeq_REQUIRED_BYTES_FOR_ACN_ENCODING);

    int error_code = 0;

    *OUT_p1_len = asn1SccMySeq_REQUIRED_BYTES_FOR_ACN_ENCODING;
    flag result = asn1SccMySeq_ACN_Encode(&var, &bit_stream, &error_code, true);

    *(uint32_t*)(OUT_p1 + 2) = 3000;
}

void testfunction_trigger_check(void)
{
}

