/* Body file for function triggerfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "triggerfunction.h"

static bool is_done = false;

void triggerfunction_startup(void)
{
}

void triggerfunction_PI_check_trigger( void )
{
	triggerfunction_RI_test_if();
}

void triggerfunction_PI_trigger(void)
{
	if(is_done){
		return;
	}

	asn1SccMyInteger param;;

	for(int i = 0; i < 10; i++){
		param = i;
		triggerfunction_RI_sporadic_if(&param);
	}

	is_done = true;
}


