/* Body file for function monitortick
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "monitortick.h"
#include <Monitor.h>

extern const uint32_t IF_USAGE_DATA;

void monitortick_startup(void)
{
}

void monitortick_PI_monitor_tick(void)
{
    Monitor_MonitoringTick();

    struct Monitor_InterfaceUsageData *const usage_data =
        (struct Monitor_InterfaceUsageData *const)&IF_USAGE_DATA;

    Monitor_GetUsageData(function_1_sporadic_if_1, &usage_data[0]);
    Monitor_GetUsageData(function_2_sporadic_if_2, &usage_data[1]);
}


