/* Body file for function adapter
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "adapter.h"
#include <string.h>
#include <assert.h>
//#include <stdio.h>

// first 29 bits are CAN-ID
// the bit 30 determines if CAN-ID is 11-bit (standard) or 29-bit (extended)
static const uint32_t canIdTypeMask = 0x20000000u;
static const uint32_t canExtendedIdMask = 0x1fffffffu;
static const uint32_t canStandardIdMask = 0x000007ffu;

void adapter_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[adapter] Startup");
}

static byte outputFrame[12];

void adapter_pong
      (const char *IN_frame, size_t IN_frame_len)

{
    // convert ACN encoded Can-Frame (represented by byte array) into format required by driver
    assert(IN_frame_len == sizeof(asn1SccCan_Frame));
    const asn1SccCan_Frame* frame = (const asn1SccCan_Frame*)IN_frame;

    uint32_t* addressWord = (uint32_t*)outputFrame;
    if(frame->id.id.kind == Can_Id_extended_id_PRESENT) {
        *addressWord = canIdTypeMask | frame->id.id.u.extended_id;
    }
    else if(frame->id.id.kind == Can_Id_standard_id_PRESENT) {
        *addressWord = frame->id.id.u.standard_id;
    }

    memcpy(&outputFrame[sizeof(uint32_t)], frame->data.arr, frame->data.nCount);

    vm_adapter_send_can_frame(PID_env, (const char*)outputFrame, frame->data.nCount + sizeof(uint32_t));
}

void adapter_receive_can_frame
      (const char *IN_frame, size_t IN_frame_len)

{
    // convert data from driver format into ACN Can-Frame format
    asn1SccCan_Frame frame;
    uint32_t word = *((const uint32_t*)IN_frame);
    if(word & canIdTypeMask) {
        frame.id.id.kind = Can_Id_extended_id_PRESENT;
        frame.id.id.u.extended_id = word & canExtendedIdMask;
    }
    else {
        frame.id.id.kind = Can_Id_standard_id_PRESENT;
        frame.id.id.u.standard_id = word & canStandardIdMask;
    }
    frame.data.nCount = IN_frame_len - sizeof(uint32_t);
    memcpy(frame.data.arr, (byte*)IN_frame + sizeof(uint32_t), IN_frame_len - sizeof(uint32_t));

    vm_adapter_ping(PID_env, (const char*)&frame, sizeof(asn1SccCan_Frame));
}


