/* Body file for function Function_52
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_52.h"

void function_52_startup(void)
{
}

void function_52_PI_PI_1
    (const asn1SccMyInteger *IN_p1)

{
    function_52_RI_PI_1(IN_p1);
}


