/* Header file for function triggerfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void triggerfunction_startup(void);

/* Provided interfaces */
void triggerfunction_PI_trigger( void );

/* Required interfaces */
extern void triggerfunction_RI_PI_1( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
