/* Body file for function monitor_tick
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "monitor_tick.h"
#include <Monitor.h>

extern const uint32_t CPU_USAGE_DATA;

void monitor_tick_startup(void)
{
}

void monitor_tick_PI_monitor_tick(void)
{
   Monitor_MonitoringTick();

   struct Monitor_CPUUsageData *const cpu_usage_data =
		(struct Monitor_CPUUsageData *const)&CPU_USAGE_DATA;
   Monitor_GetIdleCPUUsageData(cpu_usage_data);
}


