/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <stdint.h>
#include <Hal.h>

// trigger time should be 1 second and 500 milisecond but because 
// the specific time is not deterministic this is a minimum value for a trigger time
#define TRIGGER_IF_START_TIME 1499000000ul

static bool test_result = false;
static bool is_done = false;
static volatile uint64_t var = 0;

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
	if(is_done){
		return;
	}

	uint64_t time_in_ns_1 = Hal_GetElapsedTimeInNs();

	// wait some time
	for(int i = 0; i < 100000; i++){
		var = var + 1;
	}

	uint64_t time_in_ns_2 = Hal_GetElapsedTimeInNs();

	if(time_in_ns_1 > TRIGGER_IF_START_TIME && time_in_ns_1 < time_in_ns_2){
		test_result = true;
	}

	is_done = true;
}


