/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

#define TEST_FUNCTIONS_COUNT 10

static bool test_result;
static bool is_done = false;

// set of flags, each represents if communication to a given required interface has succeded
bool test_1_to_n_flag[TEST_FUNCTIONS_COUNT];

void testfunction_startup(void)
{
	for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		test_1_to_n_flag[i] = false;
	}
}

void testfunction_PI_trigger(void)
{
	if(is_done){
		return;
	}

	asn1SccMyInteger param = 13;
	testfunction_RI_PI_1(&param);

	test_result = true;
	for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		if(test_1_to_n_flag[i] == false){
			test_result = false;
			break;
		}
	}

	is_done = true;
}




