/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

static bool test_result;
static bool is_done = false;
int test_counter = 0;

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
	if(is_done){
		return;
	}

	asn1SccMyInteger param = 13;
	testfunction_RI_PI_1(&param);

	test_result = test_counter == 10;
	is_done = true;
}




