#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import subprocess
import json
import pytest
import common


def is_location_dataview_uniq(locations):
    for location in locations:
        if location["caret"]["file"].endswith("dataview-uniq.h"):
            return True
    return False


def is_warning_allowed(message):
    # File 'dataview-uniq.c' is generated by asn1scc and it contain a warning (normal gcc output)
    # dataview-uniq.c:24:27: warning: comparison is always true due to limited range of data type [-Wtype-limits]
    #  24 |     ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    # since this file is not a part of runtime nor drivers, this warning is allowed here
    return (message["kind"] == "warning" and
            message["message"] == "comparison is always true due to limited range of data type" and
            is_location_dataview_uniq(message["locations"]))


def warning_description(message):
    return json.dumps(message, sort_keys=True, indent=4)


def test_samv71_rtems_build():
    # do standard clean and build
    project_root = "samv71-rtems-c/TEST-SAMV71-FUNCTION-C-IMPLEMENTATION"
    common.do_clean_build(project_root)

    build = common.do_build(project_root, ["samv71", "debug"])
    stderr = build.stderr.decode("utf-8")
    assert build.returncode == 0, f"Compilation errors: \n{stderr}"

    partition_root = os.path.abspath(os.path.join(project_root, "work/build/node_1"))
    try:
        # clean only generated object files using generated Makefile
        process = subprocess.run(["make", "-f", "Makefile.node_1", "clean"], cwd=partition_root, shell=False, capture_output=True)
    except (OSError, ValueError, subprocess.SubprocessError):
        pytest.fail(f"Unable to clean binaries {process.stderr}")

    try:
        # compile files with additional flag to output json
        os.environ["PARTITION_1_USER_CFLAGS"] = "-fdiagnostics-format=json"
        process = subprocess.run(["make", "-f", "Makefile.node_1", "debug"], cwd=partition_root, shell=False, capture_output=True)
        # check if all generated messages are allowed
        lines = list(filter(lambda line: line, process.stderr.decode('utf-8').splitlines()))
        for line in lines:
            messages = json.loads(line)
            for message in messages:
                assert is_warning_allowed(message), f"Unexpected warning:\n{warning_description(message)}"
    except (OSError, ValueError, subprocess.SubprocessError):
        pytest.fail(f"Unable to build binaries {process.stderr}")


if __name__ == "__main__":
    test_samv71_rtems_build()
