/* Body file for function trigger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "trigger.h"
//#include <stdio.h>

static bool is_done = false;

void trigger_startup(void)
{
}

void trigger_PI_cyclic_if(void)
{
	if(is_done){
		return;
	}

	asn1SccMySeq in_param_struct;
	in_param_struct.input_data = 4001;
	in_param_struct.output_data = 1969;
	in_param_struct.validity = asn1SccMySeq_validity_invalid;

	asn1SccMyInteger in_param_int = 17;

	asn1SccMySeq out_param_struct;
	asn1SccMyInteger out_param_int;

	trigger_RI_sporadic_provided_if_no_param();
	trigger_RI_sporadic_provided_if_with_param(&in_param_struct);

	trigger_RI_protected_provided_if_no_params();
	trigger_RI_protected_provided_if_with_params_in(&in_param_int, &in_param_struct, &in_param_int, &in_param_struct, &in_param_int);
	trigger_RI_protected_provided_if_with_params_out(&out_param_int, &out_param_struct, &out_param_int, &out_param_struct, &out_param_int);

	trigger_RI_unportected_provided_if_no_params();
	trigger_RI_unprotected_provided_if_with_params_in(&in_param_int, &in_param_struct, &in_param_int, &in_param_struct, &in_param_int);
	trigger_RI_unprotected_provided_if_with_params_out(&out_param_int, &out_param_struct, &out_param_int, &out_param_struct, &out_param_int);

	is_done = true;
}


