/* Body file for function Function_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_2.h"
#include <stdint.h>
#include <string.h>

#define DUMMY_DATA_SIZE 1200

static bool is_done = false;

void function_2_startup(void)
{
}

void function_2_PI_tested_thread_2(void)
{
    if(is_done){
        return;
    }

    uint8_t test_arr[DUMMY_DATA_SIZE];
    memset(test_arr, 0xBC, DUMMY_DATA_SIZE);

    is_done = true;
}


