/* Body file for function board
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "board.h"

typedef enum  {
    IDLE,
    START_BYTE_RECEIVED,
    PARAM_BYTE_RECEIVED,
    ERROR,
} State;

static const asn1SccSmallInteger start_byte = 0x00;
static const asn1SccSmallInteger stop_byte = 0xff;

static asn1SccSmallInteger param = 0;
static State state;

void board_startup(void)
{
    state = IDLE;
}

void board_PI_ping
      (const asn1SccSmallInteger *IN_param)

{
    if(state == IDLE) {
        if(*IN_param != start_byte) {
            state = ERROR;
            return;
        }
        state = START_BYTE_RECEIVED;
        return;
    }
    if(state == START_BYTE_RECEIVED)
    {
        param = *IN_param;
        state = PARAM_BYTE_RECEIVED;
        return;
    }
    if(state == PARAM_BYTE_RECEIVED)
    {
        if(*IN_param != stop_byte)
        {
            state = ERROR;
            return;
        }
        param = param * 2;
        board_RI_pong(&start_byte);
        board_RI_pong(&param);
        board_RI_pong(&stop_byte);
        state = IDLE;
        return;
    }
}


