/* Body file for function pinger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "pinger.h"
#include <Pmc/Pmc.h>

extern Pmc pmc;
static bool test_result = FALSE;

void pinger_startup(void)
{
}

static void verify_clock_config()
{
    Pmc_MasterckConfig master_clock_config;
    Pmc_getMasterckConfig(&pmc, &master_clock_config);
    if(master_clock_config.src != Pmc_MasterckSrc_Pllack) {
        return;
    }
    if(master_clock_config.presc != Pmc_MasterckPresc_2) {
        return;
    }
    if(master_clock_config.divider != Pmc_MasterckDiv_2) {
        return;
    }
    Pmc_PllConfig pll_config;
    Pmc_getPllConfig(&pmc, &pll_config);
    if(pll_config.pllaMul != 24) {
        return;
    }
    if(pll_config.pllaDiv != 1) {
        return;
    }
    Pmc_MainckConfig main_clock_config;
    Pmc_getMainckConfig(&pmc, &main_clock_config);
    if(main_clock_config.src != Pmc_MainckSrc_RcOsc) {
        return;
    }
    if(main_clock_config.rcOscFreq != Pmc_RcOscFreq_12M) {
        return;
    }

    test_result = TRUE;
}

static void pinger_trap()
{
    asm volatile("nop");
}


void pinger_PI_pong(void)
{
    verify_clock_config();
    pinger_trap();
}


void pinger_PI_trigger(void)
{
    pinger_RI_ping();
}


