/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Monitor.h>


void testfunction_startup(void)
{
    Monitor_UnfreezeInterfaceActivationLogging();
}

void testfunction_PI_trigger_freeze( void )
{
    Monitor_FreezeInterfaceActivationLogging();
}

void testfunction_PI_trigger_check(void)
{
    struct Monitor_InterfaceActivationEntry *activation_log;
    uint32_t latest_activation_entry_index;
    uint32_t size_of_activation_log;

    Monitor_GetInterfaceActivationEntryLog(&activation_log, &latest_activation_entry_index, &size_of_activation_log);
}


