/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <stdint.h>

static bool test_result = false;
static uint32_t counter = 0;

void testfunction_startup(void)
{
}

void testfunction_PI_protected_if(const asn1SccMyInteger *IN_counter)
{
    if(*IN_counter == counter){
        counter++;
    }
}


void testfunction_PI_trigger_check(void)
{
    test_result = counter == 4;
}


