/* Body file for function triggerfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "triggerfunction.h"

void triggerfunction_RI_get_last_error(asn1SccT_Runtime_Error* err);

static bool test_result = false;

void triggerfunction_startup(void)
{
}

void triggerfunction_PI_trigger()
{
    asn1SccMyInteger var = 400;
    triggerfunction_RI_sporadic_if(&var);

    asn1SccT_Runtime_Error err;
    err.kind = T_Runtime_Error_noerror_PRESENT;
    triggerfunction_RI_get_last_error(&err);

    test_result = (err.kind == T_Runtime_Error_encodeerror_PRESENT) && (err.u.encodeerror == ERR_MYINTEGER);
}


