/* Body file for function pinger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "pinger.h"

static bool test_result = FALSE;

static void pinger_trap()
{
    asm volatile("nop");
}

void pinger_startup(void)
{
}

void pinger_PI_pong(void)
{
    test_result = TRUE;
    pinger_trap();
}


void pinger_PI_trigger(void)
{
    pinger_RI_ping();
}


