/* Body file for function Function_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_3.h"


void function_3_startup(void)
{
}

void function_3_PI_trigger_send(void)
{
   asn1SccMyInteger var = 3;
   function_3_RI_PI_1(&var);
}


