/* Body file for function Function_65
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_65.h"

void function_65_startup(void)
{
}

void function_65_PI_PI_1
    (const asn1SccMyInteger *IN_p1)

{
    function_65_RI_PI_1(IN_p1);
}


