/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

static bool test_result = false;

void testfunction_startup(void)
{
}

void testfunction_PI_sporadic_if(const asn1SccMyInteger * IN_param)
{
	if(*IN_param == 18){
		test_result = true;
	}
}


