/* Body file for function pinger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "pinger.h"
//#include <stdio.h>


void pinger_startup(void)
{
}

static bool test_result = false;

static void pinger_trap()
{
    asm volatile ("nop");
}

void pinger_PI_pong(const asn1SccMyInteger *IN_param)

{
    test_result = *IN_param == 4;
    pinger_trap();
}


void pinger_PI_trigger(void)
{
    asn1SccMyInteger param = 2;
    pinger_RI_ping(&param);
}


