/* Body file for function mock
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "mock.h"
//#include <stdio.h>


void mock_startup(void)
{
}

void mock_PI_protected_provided_if_with_params_in
      (const asn1SccMyInteger *IN_p1,
       const asn1SccMySeq *IN_p2,
       const asn1SccMyInteger *IN_p3,
       const asn1SccMySeq *IN_p4,
       const asn1SccMyInteger *IN_p5)

{
}


void mock_PI_protected_provided_if_with_params_out
      (asn1SccMyInteger *OUT_p1,
       asn1SccMySeq *OUT_p2,
       asn1SccMyInteger *OUT_p3,
       asn1SccMySeq *OUT_p4,
       asn1SccMyInteger *OUT_p5)

{
}


void mock_PI_protected_required_if_no_params(void)
{
}


void mock_PI_sporadic_required_if_no_param(void)
{
}


void mock_PI_sporadic_required_if_with_param
      (const asn1SccMySeq *IN_p1)

{
}


void mock_PI_unportected_provided_if_no_params(void)
{
}


void mock_PI_unprotected_provided_if_with_params_in
      (const asn1SccMyInteger *IN_p1,
       const asn1SccMySeq *IN_p2,
       const asn1SccMyInteger *IN_p3,
       const asn1SccMySeq *IN_p4,
       const asn1SccMyInteger *IN_p5)

{
}


void mock_PI_unprotected_required_if_with_params_out
      (asn1SccMyInteger *OUT_p1,
       asn1SccMySeq *OUT_p2,
       asn1SccMyInteger *OUT_p3,
       asn1SccMySeq *OUT_p4,
       asn1SccMyInteger *OUT_p5)

{
}


