/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

#define CPACR_ADDR 0xE000ED88UL
#define CPACR (*(volatile uint32_t *)CPACR_ADDR)
#define CP10_CP11_OFFSET 20
#define FPU_FULL_ACCESS_MODE_CP10_CP11_MASK 0xF

static bool test_result = false;

static bool is_fpu_enabled()
{
    return ((CPACR & (FPU_FULL_ACCESS_MODE_CP10_CP11_MASK << CP10_CP11_OFFSET)) == 
           (FPU_FULL_ACCESS_MODE_CP10_CP11_MASK << CP10_CP11_OFFSET));
}

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
    volatile float a = 1.5f;
    volatile float b = 2.5f;
    volatile float c;
    c = a * b;

    test_result = is_fpu_enabled() && (c == 3.75f);
}


