/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include "Fpu/Fpu.h"

static Fpu fpu;
static bool test_result = false;

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
    volatile float a = 1.5f;
    volatile float b = 2.5f;
    volatile float c;
    c = a * b;

    test_result = c == 3.75f;
}


