/* Body file for function Function_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_2.h"
#include <Hal.h>

#define NANOSECOND_IN_SECOND 1000000000UL

void function_2_startup(void)
{
}

void function_2_PI_sporadic_if
      (const asn1SccMyInteger *IN_p1)

{
    Hal_SleepNs(5 * NANOSECOND_IN_SECOND);
}


