/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Monitor.h>

extern const uint32_t QUEUE_USAGE_DATA;

static bool test_result = false;

static bool is_check_empty_done = false;

void testfunction_startup(void)
{
}

void testfunction_PI_triger_check_empty(void)
{
    if(is_check_empty_done){
        return;
    }

    int32_t *const queue_usage_data = (int32_t *const)&QUEUE_USAGE_DATA;
    queue_usage_data[0] = Monitor_GetQueuedItemsCount(function_2_sporadic_if);
    is_check_empty_done = true;
}


void testfunction_PI_trigger_check(void)
{
    int32_t *const queue_usage_data = (int32_t *const)&QUEUE_USAGE_DATA;
    queue_usage_data[1] = Monitor_GetQueuedItemsCount(function_2_sporadic_if);

    test_result = queue_usage_data[0] == 0 && queue_usage_data[1] == 3;
}


