/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

#define TEST_FUNCTIONS_COUNT 10

static bool test_result = true;
static bool is_done = false;

// set of flags, each represents if communication to a given required interface has succeded
bool test_n_to_1_flag[TEST_FUNCTIONS_COUNT];

void testfunction_startup(void)
{
   for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		test_n_to_1_flag[i] = false;
   }
}

void testfunction_PI_PI_1
      (const asn1SccMyInteger *IN_p1)

{
	switch(*IN_p1){
	case 2:
		test_n_to_1_flag[0] = true;
		break;
	case 3:
		test_n_to_1_flag[1] = true;
		break;
	case 4:
		test_n_to_1_flag[2] = true;
		break;
	case 5:
		test_n_to_1_flag[3] = true;
		break;
	case 6:
		test_n_to_1_flag[4] = true;
		break;
	case 7:
		test_n_to_1_flag[5] = true;
		break;
	case 8:
		test_n_to_1_flag[6] = true;
		break;
	case 9:
		test_n_to_1_flag[7] = true;
		break;
	case 10:
		test_n_to_1_flag[8] = true;
		break;
	case 11:
		test_n_to_1_flag[9] = true;
		break;
	}
}

void testfunction_PI_testtrigger( void )
{
	for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		if(test_n_to_1_flag[i] == false){
			test_result = false;
			break;
		}
	}
}


