/* Body file for function testtrigger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testtrigger.h"

static bool is_done = false;

void testtrigger_startup(void)
{
}

void testtrigger_PI_trigger(void)
{
	if(is_done){
		return;
	}
	testtrigger_RI_trigger_send();
	is_done = true;
}


