/* Header file for function Function_78
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void function_78_startup(void);

/* Provided interfaces */
void function_78_PI_PI_1( const asn1SccMyInteger * );

/* Required interfaces */
extern void function_78_RI_PI_1( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
