/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Hal.h>

#define TEST_CHECKS 4

static uint64_t test_times[TEST_CHECKS];
static bool test_result = false;

void testfunction_startup(void)
{
    for(int i = 0; i < TEST_CHECKS; i++){
        test_times[i] = 0;
    }
}

void testfunction_PI_trigger_check(void)
{
    for(int i = 0; i < TEST_CHECKS; i++){
        test_times[i] = Hal_GetElapsedTimeInNs();
    }

    if(test_times[0] != 0 && test_times[1] &&test_times[2] != 0 && test_times[3] != 0 &&
        test_times[0] < test_times[1] && test_times[1] < test_times[2] && test_times[2] < test_times[3] &&
        test_times[0] > 199500000 && test_times[0] < 200500000 &&
        test_times[1] > 199500000 && test_times[1] < 200500000 &&
        test_times[2] > 199500000 && test_times[2] < 200500000 &&
        test_times[3] > 199500000 && test_times[3] < 200500000){
        test_result = true;
    }
}


