/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Hal.h>

#define TEST_CHECKS 4

volatile uint64_t time_0 = 0;
volatile uint64_t time_1 = 0;
volatile uint64_t time_2 = 0;
volatile uint64_t time_3 = 0;
volatile uint64_t delta_0 = 0;
volatile uint64_t delta_1 = 0;
volatile uint64_t delta_2 = 0;

volatile bool test_result = false;

void testfunction_startup(void)
{
}

void testfunction_PI_trigger_check(void)
{
    time_0 = Hal_GetElapsedTimeInNs();
    time_1 = Hal_GetElapsedTimeInNs();
    time_2 = Hal_GetElapsedTimeInNs();
    time_3 = Hal_GetElapsedTimeInNs();
    delta_0 = time_1 - time_0;
    delta_1 = time_2 - time_1;
    delta_2 = time_3 - time_2;

    if(time_0 != 0 && time_1 != 0 && time_2 != 0 && time_3 != 0 &&
       time_0 != time_1 && time_1 != time_2 && time_2 != time_3 && 
       delta_0 <= 1000 && delta_1 <= 1000 && delta_2 <= 1000){
        test_result = true;
    }
}


