/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

bool test_result = true;

void testfunction_startup(void)
{
}

void testfunction_PI_protected_acn_if( const asn1SccMyInteger *IN_P1, const asn1SccMySeq *OUT_P2)
{
    if(*IN_P1 != 1969){
        test_result = false;
        return;
    }

    if(OUT_P2->input_data != 14 || OUT_P2->output_data != 119 || OUT_P2->validity != asn1SccMyEnum_world){
        test_result = false;
    }
}


void testfunction_PI_protected_if( const asn1SccMyInteger *IN_P1, const asn1SccMySeq *OUT_P2)
{
    if(*IN_P1 != 1969){
        test_result = false;
        return;
    }

    if(OUT_P2->input_data != 14 || OUT_P2->output_data != 119 || OUT_P2->validity != asn1SccMyEnum_world){
        test_result = false;
    }
}


void testfunction_PI_sporadic_acn_if( const asn1SccMySeq *IN_P1)
{
    if(IN_P1->input_data != 14 || IN_P1->output_data != 119 || IN_P1->validity != asn1SccMyEnum_world){
        test_result = false;
    }
}


void testfunction_PI_sporadic_if( const asn1SccMySeq *IN_P1)
{
    if(IN_P1->input_data != 14 || IN_P1->output_data != 119 || IN_P1->validity != asn1SccMyEnum_world){
        test_result = false;
    }
}

void testfunction_PI_trigger_check()
{
    asm volatile("nop"); //NOOP
}


