/* Body file for function Function_11
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_11.h"

#define TEST_FUNCTIONS_COUNT 10

static bool test_n_to_1_flag[TEST_FUNCTIONS_COUNT];
static int counter = 0;

void function_11_startup(void)
{
   for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		test_n_to_1_flag[i] = false;
   }
}

void function_11_PI_PI_1
      (const asn1SccMyInteger *IN_p1)
{
   switch(*IN_p1){
	case 1:
		test_n_to_1_flag[0] = true;
		break;
	case 2:
		test_n_to_1_flag[1] = true;
		break;
	case 3:
		test_n_to_1_flag[2] = true;
		break;
	case 4:
		test_n_to_1_flag[3] = true;
		break;
	case 5:
		test_n_to_1_flag[4] = true;
		break;
	case 6:
		test_n_to_1_flag[5] = true;
		break;
	case 7:
		test_n_to_1_flag[6] = true;
		break;
	case 8:
		test_n_to_1_flag[7] = true;
		break;
	case 9:
		test_n_to_1_flag[8] = true;
		break;
	case 10:
		test_n_to_1_flag[9] = true;
   }
   counter++;

   if(counter == 10){
      bool is_ok = true;

      for(int i = 0; i < TEST_FUNCTIONS_COUNT; i++){
		   if(test_n_to_1_flag[i] == false){
            is_ok = false;
         }
      }

      if(is_ok){
         function_11_RI_notify();
      }
   }
}


