/* Body file for function Function_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_2.h"


void function_2_startup(void)
{
}

void function_2_PI_cyclic_if_2(void)
{
    volatile int counter = 0;
    for(int i = 0; i < 1000000; i++){
        counter = counter + 1;
    }
}


