--  Body file for function pinger
--  Generated by TASTE (kazoo/templates/skeletons/ada-body/function.tmplt)
--  You can edit this file, it will not be overwritten
--
--  !! IMPORTANT                                                        !!
--  !! When you modify your design (interface view), you must update    !!
--  !! the procedures corresponding to the provided interfaces in this  !!
--  !! file. The up-to-date signatures can be found in the .ads file.   !!

with Interfaces; use Interfaces;
package body Pinger is

   procedure Pong (Param : in out asn1SccMyinteger) is
         test_result : boolean := Param = 4;
      begin
         pragma Unused(test_result);
         null;
      end Pong;
   
   
   procedure Trigger is
         param : asn1SccMyinteger := 2;
      begin
         Pinger_RI.Ping(param);
      end Trigger;


   begin
      --  Write your startup code here
      null;

end Pinger;

