--  Body file for function pinger
--  Generated by TASTE (kazoo/templates/skeletons/ada-body/function.tmplt)
--  You can edit this file, it will not be overwritten
--
--  !! IMPORTANT                                                        !!
--  !! When you modify your design (interface view), you must update    !!
--  !! the procedures corresponding to the provided interfaces in this  !!
--  !! file. The up-to-date signatures can be found in the .ads file.   !!


package body Pinger is

   procedure Pong is
   
      begin
         --  Write your code here
         null;
      end Pong;
   
   
   procedure Trigger is
   
      begin
         Pinger_RI.Ping;
      end Trigger;


   begin
      --  Write your startup code here
      null;

end Pinger;

