/* Body file for function cubesat
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "cubesat.h"

void cubesat_startup(void)
{
}

void cubesat_PI_alive
      ( const asn1SccMyInteger * IN_testparam)

{
}

static asn1SccMyInteger myNumber = 0;

void cubesat_PI_trigger(void)
{
    cubesat_RI_ping(&myNumber);
    if(myNumber == 9) {
        myNumber = 0;
    } else {
        myNumber += 1;
    }
}

void cubesat_PI_dummy_answer_large( const asn1SccLargeMessage * IN_p1)
{
}
