/* Body file for function ponger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "ponger.h"

void ponger_startup(void)
{
}

void ponger_PI_ping
      (const asn1SccMyInteger *IN_testparam)
{
    ponger_RI_pong(IN_testparam);
}


