/* Body file for function triggerfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "triggerfunction.h"

void triggerfunction_RI_get_last_error(asn1SccT_Runtime_Error* err);

static bool test_result = false;

void triggerfunction_startup(void)
{
}

void triggerfunction_PI_trigger(void)
{
    asn1SccMySeq var;
    asn1SccMyInteger var_2;

    triggerfunction_RI_protected_if(&var, &var_2);

    asn1SccT_Runtime_Error err;
    err.kind = T_Runtime_Error_noerror_PRESENT;

    triggerfunction_RI_get_last_error(&err);

    test_result = (err.kind == T_Runtime_Error_decodeerror_PRESENT) && (err.u.encodeerror == ERR_MYINTEGER);
}


