/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include "interfaces_info.h"
#include <stdint.h>
#include <string.h>
#include <rtems/score/cpu.h>
#include <rtems/score/threadimpl.h>

#define CYCLIC_IF_1_STACK_SIZE 8000
#define CYCLIC_IF_2_STACK_SIZE 5000

static bool cyclic_if_1_size_ok = false;
static bool cyclic_if_2_size_ok = false;
static bool test_result = false;

static bool thread_stack_size_visitor(Thread_Control *the_thread, void *arg)
{
    const uint32_t id = the_thread->Object.id;
    const Stack_Control *stack = &the_thread->Start.Initial_stack;

    if (threads_info[testfunction_cyclic_if_1].id == id) {

        cyclic_if_1_size_ok = stack->size == CYCLIC_IF_1_STACK_SIZE;
    }
    else if (threads_info[testfunction_cyclic_if_2].id == id) {

        cyclic_if_2_size_ok = stack->size == CYCLIC_IF_2_STACK_SIZE;
    }

    return false;
}


void testfunction_startup(void)
{
}


void testfunction_PI_cyclic_if_1(void)
{
   asm volatile("nop");
}

void testfunction_PI_cyclic_if_2(void)
{
    asm volatile("nop");
}


void testfunction_PI_trigger_check(void)
{
    rtems_task_iterate(thread_stack_size_visitor, NULL);
    test_result = cyclic_if_1_size_ok && cyclic_if_2_size_ok;
}


