/* Body file for function linux
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "linux.h"
#include <stdio.h>

static asn1SccMyInteger test_param = 0;

void linux_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[linux] Startup");
}

void linux_PI_response
      (const asn1SccMyInteger *IN_param)

{
    printf("Got response %lu\n", *IN_param);
}

void linux_PI_trigger( void )
{
    printf("Sending test %lu\n", test_param);
    linux_RI_test(&test_param);
    ++test_param;
}
