/* Body file for function Function_5
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_5.h"


void function_5_startup(void)
{
}

void function_5_PI_PI_1
    (const asn1SccMyInteger *IN_p1)

{
    asn1SccMyInteger var = 45;
    function_5_RI_PI_1(&var);
}


