/* Body file for function Function_103
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_103.h"

void function_103_startup(void)
{
}

void function_103_PI_PI_1
    (const asn1SccMyInteger *IN_p1)

{
    function_103_RI_PI_6(IN_p1);
}


