/* Body file for function triggerfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "triggerfunction.h"

#define TEST_DATA 42
#define TEST_RESULT_DATA 55

static bool test_result = false;

void triggerfunction_startup(void)
{
}

void triggerfunction_PI_trigger(void)
{
    asn1SccMyInteger var = TEST_DATA;
    triggerfunction_RI_ping(&var);
}

void triggerfunction_PI_pong(const asn1SccMyInteger *IN_P1)
{
    test_result = *IN_P1 == TEST_RESULT_DATA;
}


