/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include "interfaces_info.h"
#include <rtems.h>

#define CYCLIC_IF_1_PRIORITY 5
#define CYCLIC_IF_2_PRIORITY 13

static bool cyclic_if_1_priority_ok = false;
static bool cyclic_if_2_priority_ok = false;
static bool test_result = false;


void testfunction_startup(void)
{
}

void testfunction_PI_cyclic_if_1(void)
{
   asm volatile("nop");
}


void testfunction_PI_cyclic_if_2(void)
{
   asm volatile("nop");
}


void testfunction_PI_trigger_check(void)
{
    bool status = true;
    rtems_id scheduler_id;
    rtems_task_priority priority_1;
    rtems_task_priority priority_2;

    status = status && (rtems_task_get_scheduler(RTEMS_SELF, &scheduler_id) == RTEMS_SUCCESSFUL);
    status = status && (rtems_task_get_priority(threads_info[testfunction_cyclic_if_1].id, scheduler_id, &priority_1) == RTEMS_SUCCESSFUL);
    status = status && (rtems_task_get_priority(threads_info[testfunction_cyclic_if_2].id, scheduler_id, &priority_2) == RTEMS_SUCCESSFUL);

    test_result = status && priority_1 == CYCLIC_IF_1_PRIORITY && priority_2 == CYCLIC_IF_2_PRIORITY;
}


