/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include <Monitor.h>


static bool test_result = true;
static struct Monitor_CPUUsageData cpu_usage_data;

void testfunction_startup(void)
{
}

void testfunction_PI_trigger_check(void)
{
    Monitor_GetIdleCPUUsageData(&cpu_usage_data);

    if(cpu_usage_data.maximum_cpu_usage >= 100.0 || cpu_usage_data.maximum_cpu_usage <= 0.0 ||
       cpu_usage_data.minimum_cpu_usage >= 100.0 || cpu_usage_data.minimum_cpu_usage < 0.0 ||
       cpu_usage_data.average_cpu_usage >= cpu_usage_data.maximum_cpu_usage || cpu_usage_data.average_cpu_usage <= cpu_usage_data.minimum_cpu_usage){
        test_result = false;
    }
}


