/* Body file for function Function_3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_3.h"
#include "Monitor.h"

extern const uint32_t STACK_USAGE_DATA;
static bool test_result = false;

void function_3_startup(void)
{
}

void function_3_PI_check(void)
{
    int32_t *const tested_thread_max_stack_usage = (int32_t *const)&STACK_USAGE_DATA;
    tested_thread_max_stack_usage[1] = Monitor_GetMaximumStackUsage(function_2_tested_thread_2);

    if(tested_thread_max_stack_usage[0] == 3344 && tested_thread_max_stack_usage[1] == 1408){
        test_result = true;
    }
}


