/* Body file for function Function_3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_3.h"
#include "Monitor.h"

__attribute__((aligned(8), section(".stackusage")))
static int32_t tested_thread_max_stack_usage[2];

static bool test_result = false;

void function_3_startup(void)
{
    tested_thread_max_stack_usage[0] = 0;
    tested_thread_max_stack_usage[1] = 0;
}

void function_3_PI_check(void)
{
    tested_thread_max_stack_usage[0] = Monitor_GetMaximumStackUsage(function_1_tested_thread_1);
    tested_thread_max_stack_usage[1] = Monitor_GetMaximumStackUsage(function_2_tested_thread_2);

    if(tested_thread_max_stack_usage[0] == 1008 && tested_thread_max_stack_usage[1] == 1408){
        test_result = true;
    }
}


