/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_1.h"


void function_1_startup(void)
{
}

void function_1_PI_cyclic_if_1(void)
{
    volatile int counter = 0;
    for(int i = 0; i < 100000; i++){
        counter = counter + 1;
    }
}


