/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_1.h"
#include <FaultHandler.h>

static unsigned int counter = 0;

void function_1_startup(void)
{
	FaultHandler_Init();
}

void function_1_PI_trigger(void)
{
	if(counter == 3){

		volatile int a = 1969;
   		volatile int b = 0;
    	volatile int c = a / b;  // triggers UsageFault
    	(void)c;
	}
	counter++;
}


