/* Header file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testfunction_startup(void);

/* Provided interfaces */
void testfunction_PI_PI_1( const asn1SccMyInteger * );


void testfunction_PI_PI_2( const asn1SccMyInteger * );


void testfunction_PI_PI_3( const asn1SccMyInteger * );


void testfunction_PI_PI_4( const asn1SccMyInteger * );


void testfunction_PI_PI_5( const asn1SccMyInteger * );


void testfunction_PI_PI_6( const asn1SccMyInteger * );


void testfunction_PI_PI_7( const asn1SccMyInteger * );


void testfunction_PI_PI_8( const asn1SccMyInteger * );


void testfunction_PI_trigger_check( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
