/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

#define TEST_VECTOR_SIZE 8

static bool test_vector[TEST_VECTOR_SIZE];
static bool test_result = true;

void testfunction_startup(void)
{
   for(int i = 0; i < TEST_VECTOR_SIZE; i++){
      test_vector[i] = false;
   }
}

void testfunction_PI_trigger_check(void)
{
    for(int i = 0; i < TEST_VECTOR_SIZE; i++){
        if(test_vector[i] == false){
            test_result = false;
            break;
        }
    }
}

void testfunction_PI_PI_1
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 42){
      test_vector[0] = true;
   }
}


void testfunction_PI_PI_2
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 43){
      test_vector[1] = true;
   }
}


void testfunction_PI_PI_3
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 44){
      test_vector[2] = true;
   }
}


void testfunction_PI_PI_4
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 45){
      test_vector[3] = true;
   }
}


void testfunction_PI_PI_5
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 46){
      test_vector[4] = true;
   }
}


void testfunction_PI_PI_6
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 47){
      test_vector[5] = true;
   }
}


void testfunction_PI_PI_7
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 48){
      test_vector[6] = true;
   }
}


void testfunction_PI_PI_8
      (const asn1SccMyInteger *IN_p1)

{
   if(*IN_p1 == 49){
      test_vector[7] = true;
   }
}


