/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_1.h"
#include <Hal.h>

void function_1_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Function_1] Startup");
}

void function_1_PI_trigger(void)
{
	enum BootHelper_ResetReason reset_reason = Hal_GetResetReason();

	volatile bool test_result = reset_reason == BootHelper_ResetReason_Software;

	(void)test_result;
}


