/* Body file for function Function_10
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_10.h"

extern int test_counter;

void function_10_startup(void)
{
}

void function_10_PI_PI_1(const asn1SccMyInteger *IN_P1)
{
	if(*IN_P1 == 13){
		test_counter++;
	}
}


