/* Body file for function cubesat
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "cubesat.h"
//#include <stdio.h>


void cubesat_startup(void)
{

}

void cubesat_PI_ping
      (const asn1SccCan_Frame *IN_frame)

{
    asn1SccCan_Frame frame;
    frame.id.id.kind = Can_Id_standard_id_PRESENT;
    frame.id.id.u.standard_id = 0xa0;
    frame.data.nCount = IN_frame->data.nCount;
    for(int i = 0; i < IN_frame->data.nCount; ++i)
    {
        frame.data.arr[i] = IN_frame->data.arr[i];
    }
    cubesat_RI_pong(&frame);
}


