/* Body file for function linux
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "linux.h"
#include <stdio.h>

void linux_startup(void)
{
}

void linux_PI_pong
      (const asn1SccSmallInteger *IN_param)

{
    if(*IN_param == 6)
    {
        printf("Got valid pong\n");
    }
    else
    {
        printf("Got invalid pong\n");
    }
}

void linux_PI_trigger(void)
{
    asn1SccSmallInteger param = 3;
    linux_RI_ping(&param);
    printf("Sent ping\n");
}


