/* Body file for function cubesat
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "cubesat.h"
//#include <stdio.h>


void cubesat_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[cubesat] Startup");
}

void cubesat_PI_trigger(void)
{
   // Write your code here
}



void cubesat_PI_ping( const asn1SccMyInteger * p1)
{

}
