/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"
#include "Monitor.h"

static bool test_result = false;

void test_overflow_handler(
    const enum interfaces_enum interface,
    uint32_t number_of_overflowed_messages)
{
    if(interface == testfunction_sporadic_if && number_of_overflowed_messages == 1){
        test_result = true;
    }
}

void testfunction_startup(void)
{
    Monitor_SetMessageQueueOverflowCallback(test_overflow_handler);
}

void testfunction_PI_sporadic_if
      (const asn1SccMyInteger *IN_p1)

{
   asm volatile("nop"); //NOOP
}


void testfunction_PI_trigger_check(void)
{
   asm volatile("nop"); //NOOP
}


