/* Body file for function Function_115
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_115.h"

void function_115_startup(void)
{
}

void function_115_PI_PI_1
    (const asn1SccMyInteger *IN_p1)

{
    function_115_RI_RI_1(IN_p1);
}


