/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

static bool protected_if_tested = false;
static bool sporadic_if_tested = false;
static bool test_result = false;

void testfunction_startup(void)
{
}

void testfunction_PI_protected_if(void)
{
    protected_if_tested = true;
}


void testfunction_PI_sporadic_if(void)
{
    sporadic_if_tested = true;
}

void testfunction_PI_trigger_check(void)
{
    test_result = protected_if_tested && sporadic_if_tested;
}


